config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('docusys.users.urls', namespace='users')),
    path('', include('docusys.levels.urls', namespace='levels')),
    # path('', include('pos.categories.urls', namespace='categories')),
    path('', include('docusys.clients.urls', namespace='clients')),
    # path('', include('pos.products.urls', namespace='products')),
    # path('', include('pos.sales.urls', namespace='sales')),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)

docusys/users/urls.py
from django.urls import path
from docusys.users.views import show_home, login_view, logout_view, show_user, create_user, create_profile, show_profile, edit_user, delete_user, edit_profile, set_pwd, change_pwd, delete_profile
from docusys.levels.views import create_level_ajax

app_name = 'docusys.users'

urlpatterns = [
    path('', login_view, name='login'),
    path('logout', logout_view, name='logout'),
    path('dashboard/', show_home, name='home'),
    path('dashboard/users', show_user, name='show'),
    path('dashboard/create/user', create_user, name='create'),
    path('dashboard/edit/<int:pk>/user', edit_user, name='edit'),
    path('dashboard/delete/<int:pk>/user', delete_user, name='delete'),
    path('dashboard/set/<int:pk>/user', set_pwd, name='set'),
    path('dashboard/change/<int:pk>/user', change_pwd, name='change'),
    path('dashboard/create/user/profile', create_profile, name='createprofile'),
    path('dashboard/edit/user/<int:pk>/profile', edit_profile, name='editprofile'),
    path('dashboard/delete/user/<int:pk>/profile', delete_profile, name='deleteprofile'),
    path('dashboard/show/user/profile', show_profile, name='showprofile'),
    path('dashboard/create/user/ajax/get/level', create_level_ajax, name='getlevel'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>{%block title %} {% endblock %}</title>
    <!-- Bootstrap 3.3.7 -->
    <link
      rel="stylesheet"
      href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}"
    />
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}"
    />
    <!-- Ionicons -->
    <link
      rel="stylesheet"
      href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}"
    />
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.css' %}" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
    <link
      rel="stylesheet"
      href="{% static 'dist/css/skins/_all-skins.min.css' %}"
    />
    <!-- Google Font -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic"
    />
    <!-- DataTables -->
    <link
      rel="stylesheet"
      href="{% static 'bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'bower_components/datatables.net-bs/css/responsive.bootstrap.min.css' %}"
    />
    <link rel="icon" href="{% static 'img/templates/icono-negro.png' %}" />

    <!--Date range picker -->
    <link
      rel="stylesheet"
      href="{% static 'bower_components/bootstrap-daterangepicker/daterangepicker.css' %}"
    />

    <!-- Morris Js -->
    <link
      rel="stylesheet"
      href="{% static 'bower_components/morris.js/morris.css' %}"
    />

    {% block css %} {% endblock %}
  </head>
  <body class="hold-transition skin-blue sidebar-collapse sidebar-mini">
    <!--Header-->
    {% include "header.html" %}
    <!--Menu-->
    {% include "menu.html" %}
    <!--begin content-->
    {% block content %} {% endblock %}
    <!--footer-->
    {% include "footer.html" %}

    <!-- jQuery 3 -->
    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- jquery modalForm-->
    <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
    <!-- SlimScroll -->
    <script src="{% static 'bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'bower_components/fastclick/lib/fastclick.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
    <!-- DataTable -->
    <script src="{% static 'bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'bower_components/datatables.net-bs/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'bower_components/datatables.net-bs/js/responsive.bootstrap.min.js' %}"></script>
    <!-- SweetAlert 2 -->
    <script src="{% static 'plugins/sweetalert2/sweetalert2.all.js' %}"></script>
    <script src="{% static 'plugins/jquery-number/jquery.number.js' %}"></script>
    <!--Date range picker -->
    <script src="{% static 'bower_components/moment/min/moment.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap-daterangepicker/daterangepicker.js' %}"></script>

    <!--Morris.js charts-->
    <script src="{% static 'bower_components/raphael/raphael.min.js' %}"></script>
    <script src="{% static 'bower_components/morris.js/morris.min.js' %}"></script>

    <!--ChartJS-->
    <script src="{% static 'bower_components/chart.js/Chart.js' %}"></script>

    <!-- AdminLTE for demo purposes -->
    <!-- <script src="{% static 'js/template.js' %}"></script> -->
    <script src="{% static 'js/app.js' %}"></script>
    <script src="{% static 'js/animation.user.js' %}"></script>
    <script src="{% static 'js/animation.level.js' %}"></script>

    {% block javascript %} {% endblock %}
  </body>
</html>

templates/basemodal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>{%block title %} {% endblock %}</title>
    <!-- Bootstrap 3.3.7 -->
    <link
      rel="stylesheet"
      href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}"
    />
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}"
    />
    <!-- Ionicons -->
    <link
      rel="stylesheet"
      href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}"
    />
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.css' %}" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
    <link
      rel="stylesheet"
      href="{% static 'dist/css/skins/_all-skins.min.css' %}"
    />
    <!-- Google Font -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic"
    />
    <!-- DataTables -->
    <link
      rel="stylesheet"
      href="{% static 'bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'bower_components/datatables.net-bs/css/responsive.bootstrap.min.css' %}"
    />
    <link rel="icon" href="{% static 'img/templates/icono-negro.png' %}" />

    <!--Date range picker -->
    <link
      rel="stylesheet"
      href="{% static 'bower_components/bootstrap-daterangepicker/daterangepicker.css' %}"
    />

    <!-- Morris Js -->
    <link
      rel="stylesheet"
      href="{% static 'bower_components/morris.js/morris.css' %}"
    />

    {% block css %} {% endblock %}
  </head>
  <body class="hold-transition skin-blue sidebar-collapse sidebar-mini">
    <!--begin content-->
    {% block content %} {% endblock %}
    <!-- jQuery 3 -->
    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- jquery modalForm-->
    <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
    <!-- SlimScroll -->
    <script src="{% static 'bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'bower_components/fastclick/lib/fastclick.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
    <!-- DataTable -->
    <script src="{% static 'bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'bower_components/datatables.net-bs/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'bower_components/datatables.net-bs/js/responsive.bootstrap.min.js' %}"></script>
    <!-- SweetAlert 2 -->
    <script src="{% static 'plugins/sweetalert2/sweetalert2.all.js' %}"></script>
    <script src="{% static 'plugins/jquery-number/jquery.number.js' %}"></script>
    <!--Date range picker -->
    <script src="{% static 'bower_components/moment/min/moment.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap-daterangepicker/daterangepicker.js' %}"></script>

    <!--Morris.js charts-->
    <script src="{% static 'bower_components/raphael/raphael.min.js' %}"></script>
    <script src="{% static 'bower_components/morris.js/morris.min.js' %}"></script>

    <!--ChartJS-->
    <script src="{% static 'bower_components/chart.js/Chart.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <!-- <script src="{% static 'js/template.js' %}"></script> -->
    <script src="{% static 'js/app.js' %}"></script>
    <script src="{% static 'js/animation.user.js' %}"></script>
    <script src="{% static 'js/animation.level.js' %}"></script>

    {% block javascript %} {% endblock %}
  </body>
</html>

templates/footer.html
{% load static %}
<footer class="main-footer">
  <strong
    >Copyright &copy; 2020
    <a href="http://www.armaiden.com" target="_blank">Devnandito.</a></strong
  >
  Todos los derechos reservados
</footer>

templates/header.html
{% load static %}
<header class="main-header">
  <!--LOGOTIPO-->
  <a href="{% url 'users:home' %}" class="logo">
    <!-- logo min-->
    <span class="logo-mini">
      <img
        src="{% static 'img/templates/icono-blanco.png' %}"
        class="img-responsive"
        style="padding: 10px"
      />
    </span>
    <!-- logo normal-->
    <span class="logo-lg">
      <img
        src="{% static 'img/templates/logo-blanco-lineal.png' %}"
        class="img-responsive"
        style="padding: 10px 0px"
      />
    </span>
  </a>
  <!--BARRA DE NAVEGACION-->
  <nav class="navbar navbar-static-top" role="navigation">
    <!--Boton de navegacion-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!--Perfil de usuario-->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            {% if request.user.profile.picture.url != '' %}
            <img
              src="{{ request.user.profile.picture.url }}"
              class="user-image"
              alt=""
            />
            {% else %}
            <img
              src="{% static 'media/users/default/anonymous.png' %}"
              class="user-image"
              alt=""
            />
            {% endif %}
            <san class="hidden-xs">{{ request.user }}</san>
          </a>
          <!--Dropdown-toggle-->
          <ul class="dropdown-menu">
            <li class="user-body">
              <div class="pull-right">
                <a
                  href="{% url 'users:change' request.user.id %}"
                  class="btn btn-default btn-flat"
                  >Cambiar password</a
                >
              </div>
            </li>
            <li class="user-body">
              <div class="pull-right">
                <a
                  href="{% url 'users:logout' %}"
                  class="btn btn-default btn-flat"
                  >Salir</a
                >
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>{%block title %} {% endblock %}</title>
    <!-- Bootstrap 3.3.7 -->
    <link
      rel="stylesheet"
      href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}"
    />
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}"
    />
    <!-- Ionicons -->
    <link
      rel="stylesheet"
      href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}"
    />
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/AdminLTE.css' %}" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
    <link
      rel="stylesheet"
      href="{% static 'dist/css/skins/_all-skins.min.css' %}"
    />
    <!-- Google Font -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic"
    />
    <!-- DataTables -->
    <link
      rel="stylesheet"
      href="{% static 'bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'bower_components/datatables.net-bs/css/responsive.bootstrap.min.css' %}"
    />
    <link rel="icon" href="{% static 'img/templates/icono-negro.png' %}" />
    <!--Date range picker -->
    <link
      rel="stylesheet"
      href="{% static 'bower_components/bootstrap-daterangepicker/daterangepicker.css' %}"
    />

    <!-- Morris Js -->
    <link
      rel="stylesheet"
      href="{% static 'bower_components/morris.js/morris.css' %}"
    />

    {% block css %} {% endblock %}
  </head>
  <body
    class="hold-transition skin-blue sidebar-collapse sidebar-mini login-page"
  >
    <!--begin content-->
    {% block content %} {% endblock %}
    <!-- jQuery 3 -->
    <script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- jquery modalForm-->
    <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
    <!-- SlimScroll -->
    <script src="{% static 'bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
    <!-- FastClick -->
    <script src="{% static 'bower_components/fastclick/lib/fastclick.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'dist/js/adminlte.min.js' %}"></script>
    <!-- DataTable -->
    <script src="{% static 'bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'bower_components/datatables.net-bs/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'bower_components/datatables.net-bs/js/responsive.bootstrap.min.js' %}"></script>
    <!-- SweetAlert 2 -->
    <script src="{% static 'plugins/sweetalert2/sweetalert2.all.js' %}"></script>
    <script src="{% static 'plugins/jquery-number/jquery.number.js' %}"></script>
    <!--Date range picker -->
    <script src="{% static 'bower_components/moment/min/moment.min.js' %}"></script>
    <script src="{% static 'bower_components/bootstrap-daterangepicker/daterangepicker.js' %}"></script>

    <!--Morris.js charts-->
    <script src="{% static 'bower_components/raphael/raphael.min.js' %}"></script>
    <script src="{% static 'bower_components/morris.js/morris.min.js' %}"></script>

    <!--ChartJS-->
    <script src="{% static 'bower_components/chart.js/Chart.js' %}"></script>

    <!-- AdminLTE for demo purposes -->
    <!-- <script src="{% static 'js/template.js' %}"></script> -->
    <script src="{% static 'js/app.js' %}"></script>
    <script src="{% static 'js/animation.user.js' %}"></script>
    <script src="{% static 'js/animation.level.js' %}"></script>

    {% block javascript %} {% endblock %}
  </body>
</html>

templates/menu.html
{% load static %}

<aside class="main-sidebar">
  <section class="sidebar">
    <ul class="sidebar-menu">
      <li class="active">
        <a href="{% url 'users:home' %}">
          <i class="fa fa-home"></i>
          <span>Home</span>
        </a>
      </li>
      {% if request.user.profile.level.id == 1 %}
      <li class="treeview">
        <a href="">
          <i class="fa fa-list-ul"></i>
          <span>Cuentas</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li>
            <a href="{% url 'users:show' %}">
              <i class="fa fa-circle-o"></i>
              <span>Users</span>
            </a>
          </li>
          <li>
            <a href="{% url 'users:showprofile' %}">
              <i class="fa fa-circle-o"></i>
              <span>Profiles</span>
            </a>
          </li>
          <li>
            <a href="{% url 'levels:show' %}">
              <i class="fa fa-circle-o"></i>
              <span>Levels</span>
            </a>
          </li>
        </ul>
      </li>
      {% endif %} {% if request.user.profile.level.id == 1 or request.user.profile.level.id == 6 %}
      <li>
        <a href="#">
          <i class="fa fa-th"></i>
          <span>Category</span>
        </a>
      </li>
      <li>
        <a href="#">
          <i class="fa fa-product-hunt"></i>
          <span>Products</span>
        </a>
      </li>
      {% endif %} {% if request.user.profile.level.id == 1 or request.user.profile.level.id == 2 %}
      <li>
        <a href="{% url 'clients:show' %}">
          <i class="fa fa-users"></i>
          <span>Clients</span>
        </a>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-list-ul"></i>
          <span>Sales</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li>
            <a href="#">
              <i class="fa fa-circle-o"></i>
              <span>Manage sale</span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-circle-o"></i>
              <span>Add sale</span>
            </a>
          </li>
          <li>
            <a href="#">
              <i class="fa fa-circle-o"></i>
              <span>Report sale</span>
            </a>
          </li>
        </ul>
      </li>
      {% endif %}
    </ul>
  </section>
</aside>