config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('docusys.users.urls', namespace='users')),
    path('', include('docusys.levels.urls', namespace='levels')),
    # path('', include('pos.categories.urls', namespace='categories')),
    path('', include('docusys.clients.urls', namespace='clients')),
    # path('', include('pos.products.urls', namespace='products')),
    # path('', include('pos.sales.urls', namespace='sales')),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)

docusys/users/urls.py
from django.urls import path
from docusys.users.views import show_home, login_view, logout_view, show_user, create_user, create_profile, show_profile, edit_user, delete_user, edit_profile, set_pwd, change_pwd, delete_profile
from docusys.levels.views import create_level_ajax

app_name = 'docusys.users'

urlpatterns = [
    path('', login_view, name='login'),
    path('logout', logout_view, name='logout'),
    path('dashboard/', show_home, name='home'),
    path('dashboard/users', show_user, name='show'),
    path('dashboard/create/user', create_user, name='create'),
    path('dashboard/edit/<int:pk>/user', edit_user, name='edit'),
    path('dashboard/delete/<int:pk>/user', delete_user, name='delete'),
    path('dashboard/set/<int:pk>/user', set_pwd, name='set'),
    path('dashboard/change/<int:pk>/user', change_pwd, name='change'),
    path('dashboard/create/user/profile', create_profile, name='createprofile'),
    path('dashboard/edit/user/<int:pk>/profile', edit_profile, name='editprofile'),
    path('dashboard/delete/user/<int:pk>/profile', delete_profile, name='deleteprofile'),
    path('dashboard/show/user/profile', show_profile, name='showprofile'),
    path('dashboard/create/user/ajax/get/level', create_level_ajax, name='getlevel'),
]

docusys/users/models/profiles.py
"""Profile models."""

# Django
from django.db import models


# Models
from docusys.levels.models import Level

# Utilities
from docusys.utils.models import CustomModel

def profile_directory_path(instance, filename):
    return 'users/{0}/{1}'.format(instance.user.username, filename)

class Profile(CustomModel):
    """Profile model.

    A profile holds a user's public data like biography, picture,
    and statistics.
    """
     
    user = models.OneToOneField('users.User', on_delete=models.CASCADE)
    description = models.CharField(null=False, blank=False, max_length=255)
    level = models.ForeignKey(
        Level,
        on_delete=models.CASCADE
    )
    last_login = models.DateTimeField(blank=True, null=True)
    picture = models.ImageField(
        'profile picture',
        upload_to=profile_directory_path,
        blank=True,
        null=True
    )

    def __str__(self):
        return self.description

docusys/users/models/users.py
""" User model."""

# Django
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator

# Utilities
from docusys.utils.models import CustomModel

class User(CustomModel, AbstractUser):

    email = models.EmailField(
        'email address',
        unique=True
    )

    phone_regex = RegexValidator(
        regex=r'|+?1?\d{9,15}$',
        message="Phone number must be  entered in the format: +9999999999. Up to 15 digists allowed."
    )

    phone_number = models.CharField(max_length=17, blank=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    is_client = models.BooleanField(
        'client',
        default=True,
        help_text=(
            'Help easily distinguish users and perform queries.'
            'Clients are the main type of user'
        )
    )

    def __str__(self):
        return self.username

    def get_short_name(self):
        return self.username

docusys/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from docusys.users.models import User, Profile

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email','username', 'first_name', 'last_name', 'password1', 'password2', 'is_active')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'username', 'first_name', 'last_name', 'is_active')

class ProfileUserForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('level', 'description', 'picture',)

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('user', 'level', 'description', 'picture',)

# class CustomEditForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ('user', 'username', 'first_name', 'last_name',)
#         exclude = ('password1', 'password2',)

docusys/users/views.py
# coding=utf-8

# Django
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, SetPasswordForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Count, Sum

# Models
from docusys.users.models import User, Profile
from docusys.clients.models import Client

# Forms
from docusys.users.forms import CustomUserCreationForm, ProfileForm, ProfileUserForm, CustomUserChangeForm

# Utilities
from docusys.utils.functions import get_url, get_body

def get_name():
    name = ['Usuarios', 'usuarios', 'Usuario', 'usuario', 'Perfiles', 'perfiles', 'Perfil', 'perfil', 'Dashboard', 'password']
    return name

# Python
import datetime

@login_required()
def show_home(request):
    tmp = get_name()
    # query1 = Sale.objects.all().aggregate(Sum('net'))
    # query2 = Category.objects.count()
    # query3 = Client.objects.count()
    # query_init = Product.objects.all()
    # query4 = query_init.count()
    # query5 = query_init.order_by('-id')[:5]
    # query6 = query_init.aggregate(Sum('sales'))
    # query7 = query_init.order_by('-sales')[:5]
    template = loader.get_template('users/dashboard.html')
    context = {
        'title': get_body(tmp[8], tmp[8]),
        # 'total_sales': query1,
        # 'total_category': query2,
        # 'total_client': query3,
        # 'total_product': query4,
        # 'product_list': query5,
        # 'product_sum': query6,
        # 'product_list1': query7,
    }
    return HttpResponse(template.render(context, request))

@login_required()
def show_user(request):
    tmp = get_name()
    list_title = ['#', 'Usuario', 'Email', 'Nombre', 'Apellido', 'Foto', 'Perfil', 'Estado', 'Ultimo login', 'Acciones']
    template = loader.get_template('users/show.html')
    object_list = User.objects.all()
    context = {
        'title': get_body(tmp[3], tmp[0]),
        'object_list': object_list,
        'uri': get_url('users'),
        'list_title':list_title,
    }
    return HttpResponse(template.render(context, request))

@login_required()
def create_user(request):
    tmp = get_name()
    template = loader.get_template('users/add.html')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        form1 = ProfileUserForm(request.POST, request.FILES)
        if form.is_valid() and form1.is_valid():
            user = form.save()
            profile = form1.save(commit=False)
            profile.user = user
            profile.save()
            message = 'Los datos se guardaron correctamente!'
            tpl = loader.get_template('messages/message.html')
            contextSuccess = {
                'title': get_body(tmp[3], tmp[0]),
                'uri': get_url('users'),
                'message': message,
            }
            return HttpResponse(tpl.render(contextSuccess, request))
    else:
        form = CustomUserCreationForm()
        form1 = ProfileUserForm()
    context = {
        'title': get_body(tmp[3], tmp[0]),
        'form': form,
        'form1': form1,
        'uri': get_url('users'),
    }
    return HttpResponse(template.render(context, request))


@login_required()
def edit_user(request, pk):
    tmp = get_name()
    template = loader.get_template('users/edit.html')
    ins = get_object_or_404(User, pk=pk)
    ins1 = get_object_or_404(Profile, user=pk)
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=ins)
        form1 = ProfileUserForm(request.POST, request.FILES,  instance=ins1)
        if form.is_valid() and form1.is_valid():
            form.save()
            form1.save()
            message = 'Los datos se guardaron correctamente!'
            tpl = loader.get_template('messages/message.html')
            contextSuccess = {
                'title': get_body(tmp[3], tmp[0]),
                'uri': get_url('users'),
                'message': message,
            }
            return HttpResponse(tpl.render(contextSuccess, request))
    else:
        form = CustomUserChangeForm(instance=ins)
        form1 = ProfileUserForm(instance=ins1)
    context = {
        'title': get_body(tmp[3], tmp[0]),
        'form': form,
        'form1': form1,
        'uri': get_url('users'),
    }
    return HttpResponse(template.render(context, request))

@login_required()
def delete_user(request, pk):
    tmp = get_name()
    template = loader.get_template('users/delete.html')
    object_list = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        object_list.delete()
        return HttpResponseRedirect(reverse('users:show'))
    else:
        context = {
            'title': get_body(tmp[3], tmp[0]),
            'object_list': object_list,
            'uri': get_url('users'),
        }
    return HttpResponse(template.render(context, request))

@login_required()
def set_pwd(request, pk):
    tmp = get_name()
    template = loader.get_template('users/changepwd.html')
    ins = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        form = SetPasswordForm(ins, request.POST)
        if form.is_valid():
            form.save()
            message = 'Los datos se guardaron correctamente!'
            tpl = loader.get_template('messages/message.html')
            contextSuccess = {
                'title': get_body(tmp[3], tmp[0]),
                'uri': get_url('users'),
                'message': message,
            }
            return HttpResponse(tpl.render(contextSuccess, request))
    else:
        form = SetPasswordForm(ins)
    context = {
        'title': get_body(tmp[9], tmp[9]),
        'form': form,
        'uri': get_url('users'),
    }
    return HttpResponse(template.render(context, request))

@login_required()
def change_pwd(request, pk):
    tmp = get_name()
    template = loader.get_template('users/changepwd.html')
    ins = get_object_or_404(User, pk=pk)
    if request.method == 'POST':
        form = PasswordChangeForm(ins, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            message = 'Los datos se guardaron correctamente!'
            tpl = loader.get_template('messages/message.html')
            contextSuccess = {
                'title': get_body(tmp[3], tmp[0]),
                'uri': get_url('users'),
                'message': message,
            }
            return HttpResponse(tpl.render(contextSuccess, request))
    else:
        form = PasswordChangeForm(ins)
    context = {
        'title': get_body(tmp[9], tmp[9]),
        'form': form,
        'uri': get_url('users'),
    }
    return HttpResponse(template.render(context, request))

@login_required()
def show_profile(request):
    tmp = get_name()
    list_title = ['#', 'Usuario', 'Descripción', 'Perfil', 'Foto', 'Acciones']
    template = loader.get_template('profiles/show.html')
    object_list = Profile.objects.all()
    context = {
        'title': get_body(tmp[7], tmp[4]),
        'object_list': object_list,
        'uri': get_url('users'),
        'list_title':list_title,
    }
    return HttpResponse(template.render(context, request))

@login_required()
def create_profile(request):
    tmp = get_name()
    template = loader.get_template('profiles/add.html')
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            message = 'Los datos se guardaron correctamente!'
            tpl = loader.get_template('messages/message.html')
            contextSuccess = {
                'title': get_body(tmp[7], tmp[4]),
                'uri': get_url('users'),
                'message': message,
            }
            return HttpResponse(tpl.render(contextSuccess, request))
    else:
        form = ProfileForm()
    context = {
        'title': get_body(tmp[7], tmp[4]),
        'form': form,
        'uri': get_url('users'),
    }
    return HttpResponse(template.render(context, request))

@login_required()
def edit_profile(request, pk):
    tmp = get_name()
    template = loader.get_template('profiles/edit.html')
    ins = get_object_or_404(Profile, pk=pk)
    if request.method == 'POST':
        form = ProfileUserForm(request.POST, request.FILES, instance=ins)
        if form.is_valid():
            form.save()
            message = 'Los datos se guardaron correctamente!'
            tpl = loader.get_template('messages/message.html')
            contextSuccess = {
                'title': get_body(tmp[7], tmp[4]),
                'uri': get_url('users'),
                'message': message,
            }
            return HttpResponse(tpl.render(contextSuccess, request))
    else:
        form = ProfileUserForm(instance=ins)
    context = {
        'title': get_body(tmp[7], tmp[4]),
        'form': form,
        'uri': get_url('users'),
    }
    return HttpResponse(template.render(context, request))

@login_required()
def delete_profile(request, pk):
    tmp = get_name()
    template = loader.get_template('profiles/delete.html')
    object_list = get_object_or_404(Profile, user=pk)
    if request.method == 'POST':
        object_list.delete()
        return HttpResponseRedirect(reverse('users:showprofile'))
    else:
        context = {
            'title': get_body(tmp[7], tmp[4]),
            'object_list': object_list,
            'uri': get_url('users'),
        }

templates/users/add.html
<!--add base template-->
{% extends "base.html" %}

<!--Add extras-->
{% load changes_extras %}

<!--add format forms-->
{% load widget_tweaks %}

<!--load statics files-->
{% load staticfiles %}

<!-- Begin title-->
{%block title %}
{{ title.create }} {% endblock %}
<!-- End title-->

<!-- Begin css-->
{% block css %}
<!-- Add css-->
{% endblock %}
<!-- End css-->
{% block content %}
<div class="content-wrapper">
  <section class="content-header">
    <h1>
      {{ title.create }}
    </h1>
    <ol class="breadcrumb">
      <li>
        <a href="{% url uri.show %}"><i class="fa fa-dashboard"></i> {{ title.show }}</a>
      </li>
      <li class="active">{{ title.create }}</li>
    </ol>
  </section>
  <section class="content">
    <div class="box">
      <div class="box-header with-border">
        <div class="box-tools pull-right">
          <button
            type="button"
            class="btn btn-box-tool"
            data-widget="collapse"
            data-toggle="tooltip"
            title="Collapse"
          >
            <i class="fa fa-minus"></i>
          </button>
          <button
            type="button"
            class="btn btn-box-tool"
            data-widget="remove"
            data-toggle="tooltip"
            title="Remove"
          >
            <i class="fa fa-times"></i>
          </button>
        </div>
      </div>
      <div class="box-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <!--begin form-->
          {% for field in form.visible_fields %}
            {% if field.label_tag == '<label for="id_is_active">Active:</label>' %}
            <div class="form-group">
              <div class="input-group">
                <span class="input-group-addon"><i class="{{ field.label|replace:1 }}"></i></span>
                {% render_field field class="form-check-input" placeholder=field.label|replace:0 %}
                <strong class="text-danger">{{ field.errors }}</strong>
              </div>
            </div>
            {% else %}
            <div class="form-group">
              <div class="input-group">
                <span class="input-group-addon"><i class="{{ field.label|replace:1 }}"></i></span>
                {% render_field field class="form-control" placeholder=field.label|replace:0 %}
                <strong class="text-danger">{{ field.errors }}</strong>
              </div>
            </div>
            {% endif %}
          {% endfor %}
          <!--begin form-->
          {% for field in form1.visible_fields %}
            {% if field.label_tag == '<label for="id_level">Level:</label>' %}
            <div class="form-group">
              <div class="input-group">
                <span class="input-group-addon"><i class="{{ field.label|replace:1 }}"></i></span>
                {% render_field field class="form-control" placeholder=field.label|replace:0 %}
                <strong class="text-danger">{{ field.errors }}</strong>
                <span class="input-group-addon"><button
                  id="create-level"
                  class="btn btn-primary"
                  type="button"
                  name="button"
                >
                <i class="fa fa-plus"></i>
                </button></span>
              </div>
            </div>
            {% else %}
            <div class="form-group">
              <div class="input-group">
                <span class="input-group-addon"><i class="{{ field.label|replace:1 }}"></i></span>
                {% render_field field class="form-control" placeholder=field.label|replace:0 %}
                <strong class="text-danger">{{ field.errors }}</strong>
              </div>
            </div>
            {% endif %}
          {% endfor %}
          <div class="form-group row">
            <img src="{% static 'media/users/default/anonymous.png' %}"alt="" class="img-thumbnail preview" width="100px"/>
          </div>
          <div class="form-group row">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </section>
</div>

<!-- Modal add user-->
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

{% endblock %}
<!--Begin js-->
{% block javascript %} {% endblock %}

templates/users/changepwd.html
<!--add base template-->
{% extends "base.html" %}

<!--Add extras-->
{% load changes_extras %}

<!--add format forms-->
{% load widget_tweaks %}

<!--load statics files-->
{% load staticfiles %}

<!-- Begin title-->
{%block title %}
{{ title.show }} {% endblock %}
<!-- End title-->

<!-- Begin css-->
{% block css %}
<!-- Add css-->
{% endblock %}
<!-- End css-->
{% block content %}
<div class="content-wrapper">
  <section class="content-header">
    <h1>
      {{ title.change }}
    </h1>
    <ol class="breadcrumb">
      <li>
        <a href="{% url uri.show %}"><i class="fa fa-dashboard"></i> {{ title.show }}</a>
      </li>
      <li class="active">{{ title.change }}</li>
    </ol>
  </section>
  <section class="content">
    <div class="box">
      <div class="box-header with-border">
        <div class="box-tools pull-right">
          <button
            type="button"
            class="btn btn-box-tool"
            data-widget="collapse"
            data-toggle="tooltip"
            title="Collapse"
          >
            <i class="fa fa-minus"></i>
          </button>
          <button
            type="button"
            class="btn btn-box-tool"
            data-widget="remove"
            data-toggle="tooltip"
            title="Remove"
          >
            <i class="fa fa-times"></i>
          </button>
        </div>
      </div>
      <div class="box-body">
        <form method="post">
          {% csrf_token %}



          <!--begin form-->
          {% for field in form.visible_fields %}

            <div class="form-group">
              <div class="input-group">
                <span class="input-group-addon"><i class="{{ field.label|replace:1 }}"></i></span>
                {% render_field field class="form-control" placeholder=field.label|replace:0 %}
                <strong class="text-danger">{{ field.errors }}</strong>
              </div>
            </div>
          {% endfor %}
          <div class="form-group row">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </section>
</div>
{% endblock %}
<!--Begin js-->
{% block javascript %} {% endblock %}

templates/users/dashboard.html
<!--add base template-->
{% extends "base.html" %}

<!--Add extras-->
{% load changes_extras %}

<!--add format forms-->
{% load widget_tweaks %}

<!--load statics files-->
{% load static %}

<!--load humanize -->
{% load humanize %}

<!-- Begin title-->
{%block title %}
{{ title.home }}
{% endblock %}
<!-- End title-->

<!-- Begin css-->
{% block css %}
<!-- Add css-->
{% endblock %}
<!-- End css-->
{% block content %}
<div class="content-wrapper">
  <section class="content-header">
    <h1>
      {{ title.home }}
    </h1>
    <ol class="breadcrumb">
      <li>
        <a href="#"><i class="fa fa-dashboard"></i> Home</a>
      </li>
      <li class="active">{{ title.home }}</li>
    </ol>
  </section>

  
  <section class="content">
  {% if request.user.profile.level.id == 1 %}
  <div class="row">
    <div class="col-lg-3 col-xs-6">
      <div class="small-box bg-aqua">
        <div class="inner">
          <h3>${# { total_sales.net__sum|intcomma } #} </h3>
          <p>Ventas</p>
        </div>
        <div class="icon">
          <i class="ion ion-social-usd"></i>
        </div>
        <a href="#" class="small-box-footer">
          Mas info <i class="fa fa-arrow-circle-right"></i>
        </a>
      </div>
    </div>
    
    <div class="col-lg-3 col-xs-6">
      <div class="small-box bg-green">
        <div class="inner">
          <h3>{# { total_category } #}</h3>
          <p>Categorias</p>
        </div>
        <div class="icon">
          <i class="ion ion-clipboard"></i>
        </div>
        <a href="#" class="small-box-footer">
          Mas info <i class="fa fa-arrow-circle-right"></i>
        </a>
      </div>
    </div>
    
    <div class="col-lg-3 col-xs-6">
      <div class="small-box bg-yellow">
        <div class="inner">
          <h3>{# { total_client } #}</h3>
          <p>Clientes</p>
        </div>
        <div class="icon">
          <i class="ion ion-person-add"></i>
        </div>
        <a href="{% url 'clients:show' %}" class="small-box-footer">
          Mas info <i class="fa fa-arrow-circle-right"></i>
        </a>
      </div>
    </div>
    
    <div class="col-lg-3 col-xs-6">
      <div class="small-box bg-red">
        <div class="inner">
          <h3>{# { total_product } #}</h3>
          <p>Productos</p>
        </div>
        <div class="icon">
          <i class="ion ion-ios-cart"></i>
        </div>
        <a href="#" class="small-box-footer">
          Mas info <i class="fa fa-arrow-circle-right"></i>
        </a>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-12">
      <div class="box box-solid  bg-teal-gradient">
        <div class="box-header">
          <i class="fa fa-th"></i>
          <h3 class="box-title">Gráfico de ventas</h3>
        </div>
        <div class="box-body border-radius-none nuevoGraficoVentas">
          <div class="chart" id="line-chart-sales1" style="height: 250px;"></div>
        </div>
      </div>
    </div>
    
    <div class="col-lg-6">
      <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="box-title">Productos mas vendidos</h3>
        </div>
        <div class="box-body">
          <div class="row">
            <div class="col-md-8">
              <div class="chart-responsive">
                <canvas id="pieChart" height="150"></canvas>
              </div>
            </div>
            <div class="col-md-4">
              <ul class="chart-legend clearfix">
                {% for product in product_list1 %}
                  <li><i class="fa fa-circle-o text-{% cycle 'red' 'blue' 'green' 'purple' 'aqua' %}"></i> {{product.description}} </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
        <div class="box-footer no-padding">
          <ul class="nav nav-pills nav-stacked">
            {# % for product in product_list1 % #}
              <li><a href="#">{# {product.description} #}
                <span class="pull-right text-{% cycle 'red' 'blue' 'green' 'purple' 'aqua' %}"><i class="fa fa-angle-down"></i> {# { product.sales|percent:product_sum.sales__sum } #}%</span></a></li>  
            {# % endfor % #}
          </ul>
        </div>
      </div>
    </div>
    
    <div class="col-lg-6">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Ultimos productos agregados</h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
              <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove">
              <i class="fa fa-times"></i>
            </button>
          </div>
        </div>
        <div class="box-body">
          <ul class="products-list product-list-in-box">
            {% for product in product_list %}
            <li class="item">
              <div class="product-img">
                <img class="img" width="60px" src="{# { product.image.url } #}" alt="Product image">
              </div>
              <div class="product-info">
                <a href="" class="product-title">
                  {{ product.description }}
                  <span class="label label-warning pull-right">{# { product.sale_price|intcomma } #}</span>
                </a>
              </div>
            </li>
            {% endfor %}
          </ul>
        </div>
        <div class="box-footer text-center">
          <a href="{# % url 'products:show' % #}" class="uppercase">Ver todos los productos</a>
        </div> 
      </div>
      
    </div>
    {% else %}
    <div class="row">
      <div class="col-lg-12">
        <div class="box box-success">
          <div class="box-header">
            <h1>Welcome {{ request.user }}</h1>
          </div>
        </div>
      </div>
    </div>
    {% endif %}
  </section>
</div>
{% endblock %}
<!--Begin js-->
{% block javascript %} 
<script>
  var uri = "api/v6";
  $.ajax({
    type: "GET",
    url: uri,
    success: function (response) {
      a = response.data_sale;
      var myData = [];
      for (x = 0; x < a.length; x++) {
        y=x+1
        var obj = {
          year: a[x]["year"]+' '+'Q'+a[x]["month"],
          value: a[x]["value"]
        };
        myData.push(obj);
      }
      var line = new Morris.Line({
        element: 'line-chart-sales1',
        resize: true,
        data: myData,
        xkey: 'year',
        ykeys: ['value'],
        labels: ['Sale'],
        lineColors: ['#3c8dbc'],
        hideHover: 'auto'
      });
    },
    error: function (response) {
      console.log(response);
    },
  });

  var uri = "api/v7";
  $.ajax({
    type: "GET",
    url: uri,
    success: function (response) {
      a = response.data_product;
      var myProduct = [];
      for (x = 0; x < a.length; x++) {
        y=x+1
        var obj = {
          value: a[x]["value"],
          color: a[x]["color"],
          highlight: a[x]["highlight"],
          label: a[x]["label"]
        };
        myProduct.push(obj);
      }
      // console.log(myProduct)
      var pieChartCanvas = $('#pieChart').get(0).getContext('2d');
      var pieChart       = new Chart(pieChartCanvas);
      var PieData        = myProduct
      var pieOptions     = {
        // Boolean - Whether we should show a stroke on each segment
        segmentShowStroke    : true,
        // String - The colour of each segment stroke
        segmentStrokeColor   : '#fff',
        // Number - The width of each segment stroke
        segmentStrokeWidth   : 1,
        // Number - The percentage of the chart that we cut out of the middle
        percentageInnerCutout: 50, // This is 0 for Pie charts
        // Number - Amount of animation steps
        animationSteps       : 100,
        // String - Animation easing effect
        animationEasing      : 'easeOutBounce',
        // Boolean - Whether we animate the rotation of the Doughnut
        animateRotate        : true,
        // Boolean - Whether we animate scaling the Doughnut from the centre
        animateScale         : false,
        // Boolean - whether to make the chart responsive to window resizing
        responsive           : true,
        // Boolean - whether to maintain the starting aspect ratio or not when responsive, if set to false, will take up entire container
        maintainAspectRatio  : false,
        // String - A legend template

        // String - A tooltip template
        tooltipTemplate      : '<%=value %> <%=label%>'
      };
      // Create pie or douhnut chart
      // You can switch between pie and douhnut using the method below.
      pieChart.Doughnut(PieData, pieOptions);
      // -----------------
      // - END PIE CHART -
      // -----------------
    },
    error: function (response) {
      console.log(response);
    },
  });
  



</script>
{% endblock %}