config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('docusys.users.urls', namespace='users')),
    path('', include('docusys.levels.urls', namespace='levels')),
    # path('', include('pos.categories.urls', namespace='categories')),
    path('', include('docusys.clients.urls', namespace='clients')),
    # path('', include('pos.products.urls', namespace='products')),
    # path('', include('pos.sales.urls', namespace='sales')),
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)

docusys/clients/urls.py
from django.urls import path
from docusys.clients.views import show_client, create_client, edit_client, delete_client, create_client_ajax

app_name = 'docusys.clients'

urlpatterns = [
    path('dashboard/create/client', create_client, name='create'),
    path('dashboard/edit/<int:pk>/client', edit_client, name='edit'),
    path('dashboard/delete/<int:pk>/client', delete_client, name='delete'),
    path('dashboard/show/client', show_client, name='show'),
    path('dashboard/create/ajax/get/client', create_client_ajax, name='getclient'),
]

docusys/clients/models.py
"""Clients models."""

# Django
from django.db import models

# Utilities
from docusys.utils.models import CustomModel

class Client(CustomModel):
    """Client model."""

    first_name = models.CharField(max_length=140, blank=False, null=False)
    last_name = models.CharField(max_length=140, blank=False, null=False)
    ci = models.CharField(max_length=12, blank=False, null=False)
    birthday = models.DateField(blank=True, null=True)
    sex = models.CharField(max_length=1, blank=True, null=True)
    nationality = models.CharField(max_length=140, blank=True, null=True)
    des_type = models.CharField(max_length=140, blank=True, null=True)
    code1 = models.CharField(max_length=20, blank=True, null=True)
    code2 = models.CharField(max_length=20, blank=True, null=True)
    code3 = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    direction = models.CharField(max_length=500, blank=True, null=True)
    phone = models.CharField(max_length=10, blank=True, null=True)
    

    def __str__(self):
        return ('{} {}').format(self.first_name, self.last_name)

docusys/clients/forms.py
from django import forms
from docusys.clients.models import Client

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('first_name', 'last_name', 'ci', 'email', 'phone', 'direction', 'birthday',)

docusys/clients/views.py
# coding=utf-8

# Django
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Models
from docusys.clients.models import Client

# Forms
from docusys.clients.forms import ClientForm

# Utilities
from docusys.utils.functions import get_url, get_body

def get_name():
    name = ['Clientes', 'clientes', 'Cliente', 'cliente']
    return name

@login_required()
def show_client(request):
    tmp = get_name()
    list_title = ['#', 'Nombre', 'Apellido', 'Cedula', 'Email', 'Telefono', 'Dirección', 'Fecha cumpleaños', 'Compras', 'Acciones']
    template = loader.get_template('clients/show.html')
    object_list = Client.objects.all()
    context = {
        'title': get_body(tmp[3], tmp[0]),
        'object_list': object_list,
        'uri': get_url('clients'),
        'list_title': list_title,
    }
    return HttpResponse(template.render(context, request))

@login_required()
def create_client(request):
    tmp = get_name()
    template = loader.get_template('clients/add.html')
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            form.save()
            message = 'Los datos se guardaron correctamente!'
            tpl = loader.get_template('messages/message.html')
            contextSuccess = {
                'title': get_body(tmp[3], tmp[0]),
                'uri': get_url('clients'),
                'message': message,
            }
            return HttpResponse(tpl.render(contextSuccess, request))
    else:
        form = ClientForm()
    context = {
        'title': get_body(tmp[3], tmp[0]),
        'form': form,
        'uri': get_url('clients'),
    }
    return HttpResponse(template.render(context, request))

@login_required()
def edit_client(request, pk):
    tmp = get_name()
    template = loader.get_template('clients/edit.html')
    ins = get_object_or_404(Client, pk=pk)
    if request.method == 'POST':
        form = ClientForm(request.POST, instance=ins)
        if form.is_valid():
            form.save()
            message = 'Los datos se guardaron correctamente!'
            tpl = loader.get_template('messages/message.html')
            contextSuccess = {
                'title': get_body(tmp[3], tmp[0]),
                'uri': get_url('clients'),
                'message': message,
            }
            return HttpResponse(tpl.render(contextSuccess, request))
    else:
        form = ClientForm(instance=ins)
    context = {
        'title': get_body(tmp[3], tmp[0]),
        'form': form,
        'uri': get_url('clients'),
    }
    return HttpResponse(template.render(context, request))

@login_required()
def delete_client(request, pk):
    tmp = get_name()
    template = loader.get_template('clients/delete.html')
    object_list = get_object_or_404(Client, pk=pk)
    if request.method == 'POST':
        object_list.delete()
        return HttpResponseRedirect(reverse('clients:show'))
    else:
        context = {
            'title': get_body(tmp[3], tmp[0]),
            'object_list': object_list,
            'uri': get_url('clients'),
        }
    return HttpResponse(template.render(context, request))

@login_required()
def create_client_ajax(request):
    tmp = get_name()
    template = loader.get_template('clients/modal.html')
    if request.method == 'POST' and request.is_ajax():
        form = ClientForm(request.POST)
        if form.is_valid():
            data = form.save()
            client_info = {
                'id': data.id,
                'first_name': data.first_name,
            }
            return JsonResponse({'client_info' : client_info}, status=200)
        # else:
        #     return JsonResponse({'message': 'Error message'}, status=500)
    else:
        form = ClientForm()
    context = {
        'title': get_body(tmp[3], tmp[0]),
        'form': form,
    }
    return HttpResponse(template.render(context, request))

templates/clients/add.html
<!--add base template-->
{% extends "base.html" %}

<!--Add extras-->
{% load changes_extras %}

<!--add format forms-->
{% load widget_tweaks %}

<!--load statics files-->
{% load static %}

<!-- Begin title-->
{%block title %}
{{ title.create }} {% endblock %}
<!-- End title-->

<!-- Begin css-->
{% block css %}
<!-- Add css-->
{% endblock %}
<!-- End css-->
{% block content %}
<div class="content-wrapper">
  <section class="content-header">
    <h1>
      {{ title.create }}
    </h1>
    <ol class="breadcrumb">
      <li>
        <a href="{% url uri.show %}"><i class="fa fa-dashboard"></i> {{ title.show }}</a>
      </li>
      <li class="active">{{ title.create }}</li>
    </ol>
  </section>
  <section class="content">
    <div class="box">
      <div class="box-header with-border">
        <div class="box-tools pull-right">
          <button
            type="button"
            class="btn btn-box-tool"
            data-widget="collapse"
            data-toggle="tooltip"
            title="Collapse"
          >
            <i class="fa fa-minus"></i>
          </button>
          <button
            type="button"
            class="btn btn-box-tool"
            data-widget="remove"
            data-toggle="tooltip"
            title="Remove"
          >
            <i class="fa fa-times"></i>
          </button>
        </div>
      </div>
      <div class="box-body">
        <form method="post">
          {% csrf_token %}
          <!--begin form-->
          {% for field in form.visible_fields %}
            <div class="form-group">
              <div class="input-group">
                <span class="input-group-addon"><i class="{{ field.label|replace:1 }}"></i></span>
                {% render_field field class="form-control" placeholder=field.label|replace:0 %}
                <strong class="text-danger">{{ field.errors }}</strong>
              </div>
            </div>
          {% endfor %}
          <div class="form-group row">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </section>
</div>
{% endblock %}
<!--Begin js-->
{% block javascript %} {% endblock %}

templates/clients/delete.html
<!--add base template-->
{% extends "base.html" %}

<!--Add extras-->
{% load changes_extras %}

<!--add format forms-->
{% load widget_tweaks %}

<!--load statics files-->
{% load static %}

<!-- Begin title-->
{%block title %}
{{ title.delete }} {% endblock %}
<!-- End title-->

<!-- Begin css-->
{% block css %}
<!-- Add css-->
{% endblock %}
<!-- End css-->
{% block content %}
<div class="content-wrapper">
  <section class="content-header">
    <h1>
      {{ title.delete }}
    </h1>
    <ol class="breadcrumb">
      <li>
        <a href="{% url uri.show %}"><i class="fa fa-dashboard"></i> {{ title.show }}</a>
      </li>
      <li class="active">{{ title.delete }}</li>
    </ol>
  </section>
  <section class="content">
    <div class="box">
      <div class="box-header with-border">
        <div class="box-tools pull-right">
          <button
            type="button"
            class="btn btn-box-tool"
            data-widget="collapse"
            data-toggle="tooltip"
            title="Collapse"
          >
            <i class="fa fa-minus"></i>
          </button>
          <button
            type="button"
            class="btn btn-box-tool"
            data-widget="remove"
            data-toggle="tooltip"
            title="Remove"
          >
            <i class="fa fa-times"></i>
          </button>
        </div>
      </div>
      <div class="box-body">
        <form method="post">
          {% csrf_token %}
          <div class="box-body">
            <div class="form-group">
              <div class="input-group">
                <h4>Esta seguro que desea borrar el registro {{ object_list.ci }} ?</h4>
              </div>
            </div>
          </div>
          <div class="form-group row">
            <div class="col-sm-10">
              <a href="{% url uri.show %}" class="btn btn-primary">Volver</a>
              <button type="submit" class="btn btn-primary">Borrar</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </section>
</div>
{% endblock %}
<!--Begin js-->
{% block javascript %} {% endblock %}

templates/clients/edit.html
<!--add base template-->
{% extends "base.html" %}

<!--Add extras-->
{% load changes_extras %}

<!--add format forms-->
{% load widget_tweaks %}

<!--load statics files-->
{% load static %}

<!-- Begin title-->
{%block title %}
{{ title.edit }} {% endblock %}
<!-- End title-->

<!-- Begin css-->
{% block css %}
<!-- Add css-->
{% endblock %}
<!-- End css-->
{% block content %}
<div class="content-wrapper">
  <section class="content-header">
    <h1>
      {{ title.edit }}
    </h1>
    <ol class="breadcrumb">
      <li>
        <a href="{% url uri.show %}"><i class="fa fa-dashboard"></i> {{ title.show }}</a>
      </li>
      <li class="active">{{ title.edit }}</li>
    </ol>
  </section>
  <section class="content">
    <div class="box">
      <div class="box-header with-border">
        <div class="box-tools pull-right">
          <button
            type="button"
            class="btn btn-box-tool"
            data-widget="collapse"
            data-toggle="tooltip"
            title="Collapse"
          >
            <i class="fa fa-minus"></i>
          </button>
          <button
            type="button"
            class="btn btn-box-tool"
            data-widget="remove"
            data-toggle="tooltip"
            title="Remove"
          >
            <i class="fa fa-times"></i>
          </button>
        </div>
      </div>
      <div class="box-body">
        <form method="post">
          {% csrf_token %}
          <!--begin form-->
          {% for field in form.visible_fields %}
            <div class="form-group">
              <div class="input-group">
                <span class="input-group-addon"><i class="{{ field.label|replace:1 }}"></i></span>
                {% render_field field class="form-control" placeholder=field.label|replace:0 %}
                <strong class="text-danger">{{ field.errors }}</strong>
              </div>
            </div>
          {% endfor %}
          <div class="form-group row">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </section>
</div>
{% endblock %}
<!--Begin js-->
{% block javascript %} {% endblock %}

templates/clients/modal.html
<!--add base template-->
{% extends "basemodal.html" %}

<!--Add extras-->
{% load changes_extras %}

<!--add format forms-->
{% load widget_tweaks %}

<!--load statics files-->
{% load static %}

<!-- Begin title-->
{%block title %}
{{ title.show }} {% endblock %}
<!-- End title-->

<!-- Begin css-->
{% block css %}
<!-- Add css-->
{% endblock %}
<!-- End css-->
{% block content %}
<div class="modal-header" style="background: #3c8dbc; color: white;">
  <h2 class="modal-title" id="modal-ajax">{{ title.create }}</h2>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <form id="form-client" action="{% url 'clients:getclient' %}" method="post">
    {% csrf_token %}
    <!--begin for-->
    {% for field in form.visible_fields %}
    <div class="form-group">
      <div class="box-body">
        <div class="form-group">
          <div class="input-group">
            <span class="input-group-addon"
              ><i class="{{ field.label|replace:1 }}"></i
            ></span>
            {% render_field field class="form-control input-lg" placeholder=field.label|replace:0 %}
            <strong class="text-danger">{{ field.errors }}</strong>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    <div class="modal-footer">
      <button
        id="close"
        type="button"
        class="btn btn-default pull-left"
        data-dismiss="modal"
      >
        Close
      </button>
      <button type="submit" class="btn btn-primary">Guardar</button>
    </div>
  </form>
</div>

{% endblock %}
<!--Begin js-->
{% block javascript %}
{% endblock %}

templates/clients/show.html
<!--add base template-->
{% extends "base.html" %}

<!--Add extras-->
{% load changes_extras %}

<!--add format forms-->
{% load widget_tweaks %}

<!--load statics files-->
{% load static %}

<!-- Begin title-->
{%block title %}
{{ title.show }} {% endblock %}
<!-- End title-->

<!-- Begin css-->
{% block css %}
<!-- Add css-->
{% endblock %}
<!-- End css-->
{% block content %}
<div class="content-wrapper">
  <section class="content-header">
    <h1>
      {{ title.show }}
    </h1>
    <ol class="breadcrumb">
      <li>
        <a href="{% url uri.home %}"><i class="fa fa-dashboard"></i> {{ title.home }}</a>
      </li>
      <li class="active">{{ title.show }}</li>
    </ol>
  </section>
  <section class="content">
    <div class="box">
      <div class="box-header with-border">
        <a href="{% url uri.create %}" class="btn btn-primary"> {{ title.create }} </a>
        <div class="box-tools pull-right">
          <button
            type="button"
            class="btn btn-box-tool"
            data-widget="collapse"
            data-toggle="tooltip"
            title="Collapse"
          >
            <i class="fa fa-minus"></i>
          </button>
          <button
            type="button"
            class="btn btn-box-tool"
            data-widget="remove"
            data-toggle="tooltip"
            title="Remove"
          >
            <i class="fa fa-times"></i>
          </button>
        </div>
      </div>
      <div class="box-body">
        <table class="table table-bordered table-striped dt-responsive tablas">
          <thead>
            <tr>
            {% for title in list_title %}
              <th> {{ title }} </th>
            {% endfor %}
            </tr>
          </thead>
          <tbody>
            {% for item in object_list %}
            <tr>
              <td>{{ item.id }}</td>
              <td>{{ item.first_name }}</td>
              <td>{{ item.last_name }}</td>
              <td>{{ item.ci }}</td>
              <td>{{ item.email }}</td>
              <td>{{ item.phone }}</td>
              <td>{{ item.direction }}</td>
              <td>{{ item.birthday }}</td>
              <td>{{ item.purchases }}</td>
              <td>
                <div class="btn-groups">
                  <a href="{% url uri.edit  item.id  %}" class="btn btn-warning"><i class="fa fa-pencil"></i></a>
                  {% if request.user.profile.level.id == 1 %}
                  <a href="{% url uri.delete  item.id  %}" class="btn btn-danger"><i class="fa fa-times"></i></a>
                  {% endif %}
                </div>
              </td>
            </tr>
            {% endfor%}
          </tbody>
        </table>
      </div>
    </div>
  </section>
</div>

{% endblock %}
<!--Begin js-->
{% block javascript %}
{% endblock %}